Repository SE310-Team-1/SE310_Fitness_Tracker, pull requests merged in 2024-08, with the labels that each got.

#15 Add SonarCloud in GitHub Actions Closes #14
  .github/workflows/sonarcloud.yml
  sonar-project.properties
Labels: SetUp

#24 [Bug] create db folder solves #23
  fitness_tracker/src/App.test.js
  server/db.js
Labels: bug

#35 Feature/exercises display - Load exercise types and log completed sets on backend
  fitness_tracker/src/components/ExerciseEditor.jsx
  fitness_tracker/src/components/ExercisesDisplay.jsx
Labels: feature

#36 Feature/exercises css styling
  fitness_tracker/src/components/ExerciseEditor.jsx
  fitness_tracker/src/components/ExerciseLogger.jsx
  fitness_tracker/src/components/ExercisesDisplay.jsx
  fitness_tracker/src/components/RoutinesDisplay.jsx
  fitness_tracker/src/module_CSS/ExerciseEditor.module.css
  fitness_tracker/src/module_CSS/ExerciseLogger.module.css
  fitness_tracker/src/module_CSS/ExercisesDisplay.module.css
  fitness_tracker/src/module_CSS/RoutinesDisplay.module.css
  fitness_tracker/src/module_CSS/buttons.module.css
  fitness_tracker/src/module_CSS/colours.module.css
Labels: feature

#43 Feature/add to today workout Closes #42
  CODE_OF_CONDUCT.md
  fitness_tracker/src/App.js
  fitness_tracker/src/components/ExercisesDisplay.jsx
  fitness_tracker/src/components/NewRoutineModal.jsx
  fitness_tracker/src/components/Routine.jsx
  fitness_tracker/src/components/RoutinesDisplay.jsx
  fitness_tracker/src/components/TabDisplay.jsx
  fitness_tracker/src/module_CSS/TabDisplay.module.css
Labels: feature

#50 Bugfix/Fixed date format as 'yyyy-mm-dd' for all relevant components
  fitness_tracker/src/components/ExercisesDisplay.jsx
  fitness_tracker/src/components/GraphDisplay.jsx
  fitness_tracker/src/components/NewRoutineModal.jsx
  fitness_tracker/src/utils/dateUtils.js
Labels: bug
